services:
  pihole-unbound:
    container_name: pihole-unbound
    image: mpgirro/pihole-unbound:2025.08.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "Europe/Amsterdam"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "127.0.0.1#5335"
      FTLCONF_dns_dnssec: "true"
    volumes:
      - "/srv/docker/pihole:/etc/pihole"
      - "/srv/docker/pihole/dnsmasq:/etc/dnsmasq.d"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "dig",
          "+norecurse",
          "+retry=0",
          "@127.0.0.1",
          "pi.hole",
          "||",
          "exit",
          "1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.home`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  homelab:
    external: true
